apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "AuthenticationService.fullname" . }}
spec:
  selector:
    {{- include "AuthenticationService.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  servers:
    - port:
        targetPort: {{ .Values.service.targetPort }}
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        {{ range $key, $value := .Values.gateway.hosts }}
        - {{ $value }}
        {{ end }}