apiVersion: v1
kind: Secret
metadata:
  name: {{ include "AuthenticationService.fullname" . }}

type: Opqaue
data:
  POSTGRES_USERNAME: {{ .Values.secrets.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.jwt.private_key_b64 }}
  JWT_PUBLIC_KEY: {{ .Values.secrets.jwt.public_key_b64 }}