apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "BusinessService.fullname" . }}

data:
  POSTGRES_URI: {{ .Values.config.postgres.uri }}
  POSTGRES_PORT: {{ .Values.config.postgres.port }}