apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "BusinessService.fullname" . }}

binaryData:
  POSTGRES_URI: {{ .Values.config.postgres.uri | b64enc }}
  POSTGRES_PORT: {{ .Values.config.postgres.port | b64enc }}