apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "BusinessService.fullname" . }}
  labels:
    {{- include "BusinessService.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "BusinessService.labels" . | nindent 4 }}

  servers:
    - port:
        targetPort: {{ .Values.service.targetPort }}
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        {{ range $key, $value := .Values.gateway.hosts }}
        - {{ $value }}
        {{ end }}
