apiVersion: v1
kind: Secret
metadata:
  name: {{ include "BusinessService.fullname" . }}

data:
  POSTGRES_USER: {{ .Values.secret.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.password | b64enc}}